apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: app1
